version: 2

models:
  - name: stg_medicare_spending
    description: "Staging model for medicare spending data with cleaned and standardized fields"
    columns:
      - name: brand_name
        description: "Brand name of the drug"
        tests:
          - not_null
      - name: generic_name
        description: "Generic name of the drug"
        tests:
          - not_null
      - name: total_spending
        description: "Total spending on the drug"

  - name: fct_medicare_spending
    description: "Fact table containing medicare spending data with year-over-year analysis"
    columns:
      - name: brand_name
        description: "Brand name of the drug"
        tests:
          - not_null
          - relationships:
              to: ref('dim_drugs')
              field: brand_name
      
      - name: total_spending
        description: "Total spending on the drug"

  - name: dim_drugs
    description: "Dimension table containing unique drug information"
    columns:
      - name: drug_id
        description: "Unique identifier for the drug"
        tests:
          - unique
          - not_null
      - name: brand_name
        description: "Brand name of the drug"
        tests:
          - not_null 