medicare_analytics_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: BROOPBW-PY94345
      user: LOKILOK12
      password: "{{ env_var('snowflake_password') }}"
      role: MEDICARE_ANALYST
      database: MEDICARE_DB
      warehouse: DBT_WH
      schema: dbt_schema
      threads: 4